---
language: java
sudo: false
script: mvn clean verify

deploy:
   provider: cloudfoundry
   username: richar.fernandez@unmsm.edu.pe
   password: ric.fevil.Pivotal.123
   api: https://api.run.pivotal.io
   organization: rfernandezv
   space: development