---
language: java
jdk:
- oraclejdk8
sudo: false
before_install:
  - chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify


deploy:
   provider: cloudfoundry
   username: richar.fernandez@unmsm.edu.pe
   password: ric.fevil.Pivotal.123
   api: https://api.run.pivotal.io
   organization: rfernandezv
   space: development