---
language: java
sudo: false
before_install:
  - chmod +x mvnw
install:
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean verify


deploy:
   provider: cloudfoundry
   username: richar.fernandez@unmsm.edu.pe
   password: xxxxxx
   api: https://api.run.pivotal.io
   organization: xxxxxxxxx
   space: development
